name: laravel-ci-class

on:
  push:
    branches:
      - main
      - develop
      - feature/implement-ci-github-actions
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: microsites-test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: json, dom, curl, libxml, mbstring

      - name: Check PHP
        run: php -v

      - uses: actions/checkout@v2

      - name: run composer install
        run: composer install -n --prefer-dist

      - name: Copy
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate application key
        run: php artisan key:generate

      - name: Configure database
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: run npm install
        run: npm install

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Migrate database
        run: php artisan migrate --force

      - name: Run tests with coverage
        run: php artisan test --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml