name: Microsites CI

on:
  push:
    branches:
      - main
      - develop
      - feat/user-role-management
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Check PHP
        run: php -v

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run composer install
        run: composer install -n --prefer-dist

      - name: Copy
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
      
      - name: run npm install
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Migrate database
        run: php artisan migrate

      - name: Run tests with coverage
        run: php artisan test --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml